/* Generated By:JavaCC: Do not edit this line. AdderConstants.java */
package org.zhl.demo;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AdderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTERGER = 2;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<INTERGER>",
    "\"+\"",
  };

}
